config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'shelves/show'
  devise_for :users, controllers: { registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login',
                                             sign_up: 'register',
                                             sign_out: 'logout' }

  authenticated :user do
    root 'feed#index', as: :authenticated_user
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :authors, only: %i[index show], param: :name do
    member do
      post 'follow', to: 'followships#create'
      delete 'unfollow', to: 'followships#destroy'
    end
  end

  resources :books, only: %i[index show new create] do
    member do
      post 'add', to: 'book_additions#create'
      delete 'remove', to: 'book_additions#destroy'
    end
  end
  resources :users, only: %i[index show], path: '', param: :username do
    resource :shelf, only: %i[show]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  before_create :generate_slug

  has_many :books, dependent: :destroy
  has_many :followships,
           foreign_key: :author_id,
           inverse_of: :author,
           dependent: :destroy
  has_many :followers, through: :followships, source: :user

  # instance methods
  def to_param
    name
  end
  
  private

  def generate_slug
    name.downcase.tr(' ', '-')
  end
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :title, :description, :cover, presence: true
  validates :isbn, :isbn13,
            format: { with: /\A(97(8|9))?\d{9}(\d|X)\z/ },
            presence: true

  belongs_to :author
  has_many :book_additions, dependent: :destroy
  has_many :shelves, through: :book_additions
  has_one_attached :cover, dependent: :destroy
end

app/models/book_addition.rb
# frozen_string_literal: true

class BookAddition < ApplicationRecord
  enum status: { unread: 0, currently_reading: 1, read: 2 }

  enum is_approved: { unapproved: 'unapproved',
                      approved: 'approved',
                      approved_rejected: 'approved_rejected',
                      unapproved_rejected: 'unapproved_rejected' }

  belongs_to :book
  belongs_to :shelf

  validates :book, uniqueness: { scope: :shelf_id }
end

app/models/followship.rb
# frozen_string_literal: true

class Followship < ApplicationRecord
  # associations
  belongs_to :user, counter_cache: :followings_count
  belongs_to :author, counter_cache: :followers_count

  # validations
  validates :user, uniqueness: { scope: :author_id }
end

app/models/shelf.rb
# frozen_string_literal: true

class Shelf < ApplicationRecord
  # associations
  belongs_to :user
  has_many :book_additions, dependent: :destroy
  has_many :books, through: :book_additions

  # instance methods
  def shelf_books
    books.select('books.*, book_additions.status')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validations
  validates :username,
            presence: true,
            uniqueness: true,
            format: { with: /\A[a-zA-Z0-9_\.]*\z/ }

  # associations
  has_one_attached :avatar, dependent: :destroy
  has_one :shelf, dependent: :destroy
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships, source: :author

  # instance methods
  def add_book_to_shelf(book)
    shelf.books << book
  end

  def already_added?(book)
    shelf.books.include?(book)
  end

  def remove_book_from_shelf(book)
    shelf.books.destroy(book)
  end

  def follow(author)
    followings << author
  end

  def unfollow(author)
    followings.destroy author
  end

  def following?(author)
    following_ids.include? author.id
  end

  def to_param
    username
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find_by(name: params[:name])
    @books = @author.books
  end
end

app/controllers/book_additions_controller.rb
# frozen_string_literal: true

class BookAdditionsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.add_book_to_shelf(book)
    redirect_back(fallback_location: root_path)
    flash[:notice] = "Book #{book.title} is added to your library"
  end

  def destroy
    current_user.remove_book_from_shelf(book)
    redirect_back(fallback_location: root_path)
    flash[:notice] = "Book #{book.title} is removed from your library"
  end

  def update
    current_user.mark_book_as(params[:status])
    redirect_back(fallback_location: root_path)
    flash[:notice] = "Book #{book.title} is removed from your library"
  end

  private

  def book
    @book ||= Book.find(params[:id])
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @book = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, flash: { notice: 'Book Added' }
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :isbn,
                                 :isbn13, :edition, :cover)
  end
end

app/controllers/feed_controller.rb
# frozen_string_literal: true

class FeedController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all.take(20)
  end
end

app/controllers/followships_controller.rb
# frozen_string_literal: true

class FollowshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(author)
    redirect_back(fallback_location: root_path)
    flash[:notice] = "You are now following #{author.name}"
  end

  def destroy
    current_user.unfollow(author)
    redirect_back(fallback_location: root_path)
    flash[:notice] = "You have un-followed #{author.name}"
  end

  private

  def author
    @author ||= Author.find_by(name: params[:name])
  end
end

app/controllers/shelves_controller.rb
# frozen_string_literal: true

class ShelvesController < ApplicationController
  def show
    @shelf_books = current_user.shelf.shelf_books
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nav_bar
    render 'navbar' if current_user
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_additions_helper.rb
# frozen_string_literal: true

module BookAdditionsHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
  def book_addition_button(book)
    if current_user.already_added?(book)
      link_to 'Remove book', remove_book_path(book), method: :delete
    else
      link_to 'Add book', add_book_path(book), method: :post
    end
  end

  def book_status(show_book_status, &block)
    tag.div(&block) if show_book_status
  end

  def statuses_options
    BookAddition.statuses.map { |k, v| [k.humanize, v] }
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/followships_helper.rb
# frozen_string_literal: true

module FollowshipsHelper
  def follow_button(author)
    if current_user.following?(author)
      link_to 'Unfollow', unfollow_author_path(author), method: :delete
    else
      link_to 'Follow', follow_author_path(author), method: :post
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_navbar.html.erb
<header class="lg:px-16 px-6 bg-white flex flex-wrap items-center lg:py-0 py-2 shadow-md">
  <div class="flex-1 flex justify-between items-center">
    <a href="/">
      <p class="text-blue-500 text-2xl font-bold">BookHub</p>
    </a>
  </div>
  <label for="menu-toggle" class="pointer-cursor lg:hidden block">
    <svg class="fill-current text-gray-900" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
      <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
    </svg>
  </label>
  <input class="hidden" type="checkbox" id="menu-toggle" />
  <div class="hidden lg:flex lg:items-center lg:w-auto w-full" id="menu">
    <nav>
      <ul class="lg:flex items-center justify-between text-base text-gray-700 pt-4 lg:pt-0">
        <li><a class="lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" href="/">Home</a></li>
        <li><a class="lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400 lg:mb-0 mb-2" href="#">Browse</a></li>
      </ul>
    </nav>
    <div class="relative group">
      <div class="flex items-center cursor-pointer text-sm text-blue border border-white border-b-0 group-hover:border-grey-light rounded-t-lg py-1 px-2">
        <%= image_tag(current_user.avatar, class: 'avatar-sm') %>
        <p class="pl-1 text-lg"><%= current_user.username %></p>
        <svg class="fill-current h-4 w-4" viewBox="0 0 20 20">
          <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
        </svg>
      </div>
      <div class="absolute arrow-box items-center border rounded-b-lg bg-white invisible group-hover:visible w-32">
        <%= link_to('Profile', current_user, class: 'px-4 py-2 block text-black hover:bg-gray-200') %>
        <%= link_to('Edit Profile', edit_user_registration_path, class: 'px-4 py-2 block text-black hover:bg-gray-200') %>
        <%= link_to('My Books', user_shelf_path(current_user), class: 'px-4 py-2 block text-black hover:bg-gray-200') %>
        <hr class="border-t mx-2 border-gray-400">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'px-4 py-2 block text-black hover:bg-gray-200') %>
      </div>
    </div>
  </div>
</header>

app/views/feed/index.html.erb
<div class="flex flex-col justify-start mx-auto w-3/5">
  <%= render @books, show_book_status: false %>
</div>